function cfind() {
    job_count=$(($(grep -c ^processor /proc/cpuinfo)-2))
    find . -type f -name "${1}" -print0 | xargs -0 -n1 -P${job_count} grep "${2}" -Hn"${3}"
}

# docker aliases
# bitnami/git provides a more recent version but the size is ~600MB as opposed to ~30MB
alias d-git="docker run -ti --rm -v ${HOME}:/root -v $(pwd):/git alpine/git:latest"
alias i="ip -c -brie a"
alias tpr="tput reset"

